"""MemoryManager — the single chokepoint for runtime tutor memory.

PIVOT_ROADMAP.md §7.4 declares this is the ONLY way the agent loop
builds Working memory. No service may reach into DuckDB, Qdrant, or the
filesystem during a turn — everything goes through here. That single
rule is what lets us swap the storage tier per device (DuckDB → SQLite,
Qdrant → sqlite-vss) without touching the agent.

What this Phase-A-final slice does:

- ``__init__``        bootstraps ``data/memory/`` (creates the standard
                      sub-tree, runs an idempotent ``git init`` so every
                      change becomes a reviewable diff, writes the
                      in-memory ``.gitignore`` the first time).
- ``recall(...)``     dispatches to the per-tool ``RecallPolicy`` table
                      (``backend.memory.policies``). Falls back to an
                      empty ``Recall`` (and a ``stub:true`` trace row)
                      only when no policy matches.
- ``write_event(...)`` appends one JSON line to the active per-session
                      JSONL file via a 250 ms write-back buffer with
                      fsync on flush. Files rotate at 10 MB to keep
                      readers cheap (``<sid>.0001.jsonl``,
                      ``<sid>.0002.jsonl``, ...).
- ``close_turn(sid)`` flushes the buffer.
- ``close_session(sid)`` flushes, snapshots ``mastery.parquet`` and
                      appends a row to ``sessions/index.parquet``.
- ``snapshot_mastery()`` writes ``learner/mastery.parquet`` atomically
                      via ``backend.memory.store_parquet``.
- ``compact(...)``    no-op stub; Phase B owns the real compaction loop.

The crash-injection durability test (A.15) and the multi-resolution
summaries / fact sheets (Phase B) are layered on top of this contract
without changing it.
"""

from __future__ import annotations

import glob
import json
import logging
import os
import subprocess
import threading
import time
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from backend.config import PROJECT_ROOT

logger = logging.getLogger(__name__)


# Flush every N events OR every flush_interval_ms — whichever first. This
# is the §7.8 "Field-tier" knob; flagship can leave it tighter (50 ms)
# once the real recall is in place.
_DEFAULT_FLUSH_INTERVAL_MS = 250
_DEFAULT_BUFFER_HIGH_WATER = 32

# Rotate JSONL files at 10 MB so a single grep / pyarrow read of a
# session's history never has to chew through a multi-GB blob.
_DEFAULT_ROTATION_BYTES = 10 * 1024 * 1024

# Memory root may be overridden via env so the milestone demo script
# (and any future smoke harness) can run against a tmp dir without
# touching the real ``data/memory/`` audit trail.
_MEMORY_ROOT = Path(
    os.environ.get("LINGUAMATE_MEMORY_ROOT") or (PROJECT_ROOT / "data" / "memory")
).resolve()

# Sub-tree we guarantee exists under data/memory/. Adding a new directory
# here is the only thing required to make MemoryManager treat it as part
# of the audit trail.
_AUDIT_SUBDIRS = (
    "learner",
    "evidence",
    "sessions",
    "konversation",
    "captures",
    "facts",
    "compaction",
)

# What we deliberately keep OUT of git. Image blobs are huge and have no
# review value; everything else (markdown, JSON, Parquet snapshots) is
# small and worth diffing.
_GITIGNORE_BODY = """\
# Generated by MemoryManager — keep image blobs out of git.
captures/img/
*.tmp
"""

_SCHEMA_VERSION = 1


# ─── Public types ────────────────────────────────────────────────────────


@dataclass
class Event:
    """One thing that happened in a turn — destined for the JSONL ledger.

    ``payload`` carries arbitrary JSON-serialisable detail (tool args,
    tool result, model thought chunk, recall trace summary, etc.). The
    ``kind`` is a short string namespace ('tool_intent', 'tool_result',
    'thought', 'turn_open', 'turn_close', ...).
    """

    session_id: str
    kind: str
    payload: dict[str, Any] = field(default_factory=dict)
    occurred_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="milliseconds")
    )
    v: int = _SCHEMA_VERSION

    def to_json_line(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, sort_keys=False) + "\n"


@dataclass(frozen=True)
class Section:
    """One labelled slice loaded into Working memory by ``recall()``.

    The agent renders these as labelled sections in the prompt so the
    model knows what it's reading ("recent_evidence", "fact_sheet",
    "transcript_excerpt", ...). ``tokens`` is an estimate, used only for
    budget bookkeeping.
    """

    label: str
    text: str
    tokens: int = 0


@dataclass(frozen=True)
class Recall:
    """The bundle returned by ``MemoryManager.recall(...)``.

    Always non-None even when empty. ``trace_id`` lets us correlate the
    recall with its entry in ``recall_trace.jsonl`` when we debug
    "why did Mira hallucinate that?".
    """

    tier1: list[Section] = field(default_factory=list)
    tier2: list[Section] = field(default_factory=list)
    tier3: list[Section] = field(default_factory=list)
    used_tokens: int = 0
    trace_id: str = ""

    @classmethod
    def empty(cls) -> "Recall":
        return cls(trace_id=str(uuid.uuid4()))


@dataclass(frozen=True)
class RecallContext:
    """Inputs given to a ``RecallPolicy.build`` callable.

    Kept separate from the public ``Recall`` so policies can grow (DB
    handles, sentence embedders, etc.) without expanding the public
    API surface of MemoryManager.
    """

    tool_hint: str
    observation: Any
    args: dict[str, Any]
    budget_tokens: int


# ─── MemoryManager ───────────────────────────────────────────────────────


class MemoryManager:
    """Append-only JSONL writer with write-back buffer + fsync on flush.

    Threading: ``write_event`` may be called from any FastAPI worker. We
    serialise writes per session under a per-session lock so a single
    JSONL file always sees ordered, line-aligned appends.
    """

    def __init__(
        self,
        *,
        root: Optional[Path] = None,
        flush_interval_ms: int = _DEFAULT_FLUSH_INTERVAL_MS,
        buffer_high_water: int = _DEFAULT_BUFFER_HIGH_WATER,
        rotation_bytes: int = _DEFAULT_ROTATION_BYTES,
        init_git: bool = True,
    ) -> None:
        self._root = (root or _MEMORY_ROOT).resolve()
        self._sessions_dir = self._root / "sessions"
        self._learner_dir = self._root / "learner"
        self._recall_trace_path = self._root / "recall_trace.jsonl"

        self._flush_interval_s = flush_interval_ms / 1000.0
        self._buffer_high_water = buffer_high_water
        self._rotation_bytes = rotation_bytes
        self._init_git = init_git

        self._buffers: dict[str, list[str]] = {}
        self._buffer_bytes: dict[str, int] = {}
        self._last_flush: dict[str, float] = {}
        self._sequence: dict[str, int] = {}
        self._locks: dict[str, threading.Lock] = {}
        self._lock_table = threading.Lock()

        self._ensure_audit_trail()

    # ── audit-trail bootstrap ──────────────────────────────────────────

    def _ensure_audit_trail(self) -> None:
        """Create the standard memory tree + idempotent ``git init``.

        Never raises. Called from ``__init__`` so a fresh checkout
        becomes a reviewable filesystem on first server boot.
        """
        try:
            self._root.mkdir(parents=True, exist_ok=True)
            for sub in _AUDIT_SUBDIRS:
                (self._root / sub).mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.warning("could not bootstrap memory tree: %s", exc)
            return

        gitignore = self._root / ".gitignore"
        if not gitignore.exists():
            try:
                gitignore.write_text(_GITIGNORE_BODY, encoding="utf-8")
            except OSError as exc:  # pragma: no cover
                logger.warning("could not write %s: %s", gitignore, exc)

        if not self._init_git:
            return
        if (self._root / ".git").exists():
            return
        try:
            subprocess.run(
                ["git", "init", "--quiet", str(self._root)],
                check=False,
                capture_output=True,
                timeout=10,
            )
        except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover
            logger.info("git init in memory root skipped: %s", exc)

    # ── recall ─────────────────────────────────────────────────────────

    def recall(
        self,
        *,
        tool_hint: str = "open_turn",
        observation: Any = None,
        args: Optional[dict[str, Any]] = None,
        budget_tokens: int = 4000,
    ) -> Recall:
        """Dispatch to the per-tool RecallPolicy and write a trace row.

        Falls back to ``Recall.empty()`` plus a ``stub: true`` trace row
        when no policy matches — keeps the agent loop simple even when
        we add a new tool before adding its policy.
        """
        from backend.memory.policies import find_policy  # noqa: WPS433 (cycle guard)

        started = time.perf_counter()
        ctx = RecallContext(
            tool_hint=tool_hint,
            observation=observation,
            args=args or {},
            budget_tokens=budget_tokens,
        )
        policy = find_policy(tool_hint)
        recall: Recall
        dropped: Any = False
        policy_name: Optional[str] = None
        if policy is None:
            recall = Recall.empty()
            stub = True
        else:
            policy_name = policy.tool_hint
            try:
                recall = policy.build(ctx)
            except Exception as exc:  # pragma: no cover — never break the turn
                logger.warning("recall policy %r failed: %s", policy_name, exc)
                recall = Recall.empty()
                dropped = f"policy_error:{type(exc).__name__}"
            stub = False
            recall, was_dropped = _enforce_budget(recall, budget_tokens)
            if was_dropped:
                dropped = "over_budget"

        latency_ms = round((time.perf_counter() - started) * 1000, 2)
        trace = {
            "v": _SCHEMA_VERSION,
            "ts": datetime.now(timezone.utc).isoformat(timespec="milliseconds"),
            "trace_id": recall.trace_id,
            "tool_hint": tool_hint,
            "policy": policy_name,
            "args": args or {},
            "budget_tokens": budget_tokens,
            "loaded_tokens": recall.used_tokens,
            "tier1_sections": len(recall.tier1),
            "tier2_sections": len(recall.tier2),
            "tier3_sections": len(recall.tier3),
            "tier1_tokens": sum(s.tokens for s in recall.tier1),
            "tier2_tokens": sum(s.tokens for s in recall.tier2),
            "tier3_tokens": sum(s.tokens for s in recall.tier3),
            "latency_ms": latency_ms,
            "dropped": dropped,
        }
        if stub:
            trace["stub"] = True
        try:
            with self._recall_trace_path.open("a", encoding="utf-8") as f:
                f.write(json.dumps(trace, ensure_ascii=False) + "\n")
        except OSError as exc:  # pragma: no cover
            logger.warning("recall_trace write failed: %s", exc)

        return recall

    # ── write path ─────────────────────────────────────────────────────

    def write_event(self, event: Event) -> None:
        """Append one event to the session JSONL via the write-back buffer.

        Flushes synchronously to disk if (a) the buffer crossed the
        high-water mark or (b) more than ``flush_interval_ms`` have
        passed since the last flush. ``close_turn`` / ``close_session``
        always force a flush so a turn never returns to the caller with
        unwritten events.
        """
        sid = event.session_id
        lock = self._lock_for(sid)
        line = event.to_json_line()
        line_bytes = len(line.encode("utf-8"))
        now = time.monotonic()
        flush_now = False
        with lock:
            buf = self._buffers.setdefault(sid, [])
            buf.append(line)
            self._buffer_bytes[sid] = self._buffer_bytes.get(sid, 0) + line_bytes
            last = self._last_flush.get(sid, 0.0)
            if (
                len(buf) >= self._buffer_high_water
                or (now - last) >= self._flush_interval_s
            ):
                flush_now = True
        if flush_now:
            self._flush(sid)

    def close_turn(self, session_id: str) -> None:
        """Flush the write-back buffer for the given session."""
        self._flush(session_id)

    def close_session(self, session_id: str) -> None:
        """Flush + record a `session_close` marker + Parquet snapshots."""
        self.write_event(
            Event(session_id=session_id, kind="session_close", payload={})
        )
        self._flush(session_id)
        # B.12 — produce the gist + summ MDs before snapshotting / indexing
        # so a downstream reader (Atrium "letztes Mal:") sees them as soon
        # as the session is closed. Best-effort.
        try:
            from backend.memory import summariser as _summariser  # noqa: WPS433

            files = self.list_session_files(session_id)
            if files:
                summary = _summariser.summarise_session(session_id, files)
                _summariser.write_summary_files(self._sessions_dir, summary)
        except Exception as exc:  # pragma: no cover
            logger.warning("summariser on close_session failed: %s", exc)
        try:
            self.snapshot_mastery()
        except Exception as exc:  # pragma: no cover
            logger.warning("snapshot_mastery on close_session failed: %s", exc)
        try:
            from backend.memory import store_parquet  # noqa: WPS433

            store_parquet.append_session_index_row(
                self._learner_dir.parent / "sessions" / "index.parquet",
                {
                    "session_id": session_id,
                    "closed_at": datetime.now(timezone.utc).isoformat(),
                    "files": sorted(
                        p.name for p in self.list_session_files(session_id)
                    ),
                },
            )
        except Exception as exc:  # pragma: no cover
            logger.warning("session index append failed: %s", exc)

    def snapshot_mastery(self) -> Optional[Path]:
        """Write ``data/memory/learner/mastery.parquet`` atomically.

        Returns the destination path, or ``None`` if pyarrow is missing
        / the table is empty (we still log; the caller never sees an
        exception).
        """
        try:
            from backend.memory import store_parquet  # noqa: WPS433

            dest = self._learner_dir / "mastery.parquet"
            return store_parquet.snapshot_mastery(dest)
        except Exception as exc:  # pragma: no cover
            logger.warning("snapshot_mastery failed: %s", exc)
            return None

    def compact(self, deadline_ms: int = 30_000) -> Any:
        """Run one idempotent background compaction pass (PIVOT_ROADMAP §B.16).

        Locks ``compaction/locks/compactor.lock``, summarises closed
        sessions without a gist, archives stale evidence for highly
        mastered competencies, and writes ``compaction/last_run.json``
        for resumability.

        Returns the ``CompactionReport`` so the admin endpoint can
        surface what happened. Raises ``CompactionLockedError`` when a
        prior run still holds the lock — callers should treat that as
        "try again later".
        """
        from backend.memory import compactor  # noqa: WPS433 (cycle guard)

        return compactor.run_for_manager(self, deadline_ms=deadline_ms)

    # ── read helpers ───────────────────────────────────────────────────

    def list_session_files(self, session_id: str) -> list[Path]:
        """Return all rotated JSONL files for ``session_id`` in order."""
        safe = _safe_session_segment(session_id)
        pattern = str(self._sessions_dir / f"{safe}.*.jsonl")
        files = [Path(p) for p in glob.glob(pattern)]
        files.sort(key=lambda p: p.name)
        return files

    def read_session_events(self, session_id: str) -> list[dict[str, Any]]:
        """Concatenate every rotated JSONL into one ordered list of events.

        Tolerates a torn last line in the final file (only) — that's the
        crash-injection contract enforced by ``test_memory_durability``.
        """
        events: list[dict[str, Any]] = []
        files = self.list_session_files(session_id)
        for i, path in enumerate(files):
            is_last = i == len(files) - 1
            try:
                with path.open("r", encoding="utf-8") as f:
                    lines = f.readlines()
            except OSError:
                continue
            for j, raw in enumerate(lines):
                raw = raw.rstrip("\n")
                if not raw:
                    continue
                try:
                    events.append(json.loads(raw))
                except json.JSONDecodeError:
                    if is_last and j == len(lines) - 1:
                        # Tolerated torn line.
                        continue
                    raise
        return events

    # ── helpers ────────────────────────────────────────────────────────

    def _lock_for(self, session_id: str) -> threading.Lock:
        with self._lock_table:
            lock = self._locks.get(session_id)
            if lock is None:
                lock = threading.Lock()
                self._locks[session_id] = lock
        return lock

    def _current_path(self, session_id: str, *, additional_bytes: int = 0) -> Path:
        """Return the JSONL path the next write should go to.

        Bumps the per-session sequence number when the active file plus
        the pending bytes would exceed the rotation threshold.
        """
        safe = _safe_session_segment(session_id)
        seq = self._sequence.get(session_id)
        if seq is None:
            seq = self._discover_sequence(safe)
            self._sequence[session_id] = seq

        path = self._path_for_seq(safe, seq)
        try:
            current_size = path.stat().st_size if path.exists() else 0
        except OSError:
            current_size = 0
        if current_size + additional_bytes > self._rotation_bytes and current_size > 0:
            seq += 1
            self._sequence[session_id] = seq
            path = self._path_for_seq(safe, seq)
        return path

    def _path_for_seq(self, safe: str, seq: int) -> Path:
        return self._sessions_dir / f"{safe}.{seq:04d}.jsonl"

    def _discover_sequence(self, safe: str) -> int:
        existing = sorted(
            self._sessions_dir.glob(f"{safe}.*.jsonl"),
            key=lambda p: p.name,
        )
        if not existing:
            return 1
        last = existing[-1].stem  # e.g. "<sid>.0003"
        try:
            return int(last.rsplit(".", 1)[1])
        except (IndexError, ValueError):
            return 1

    def _flush(self, session_id: str) -> None:
        lock = self._lock_for(session_id)
        with lock:
            buf = self._buffers.get(session_id) or []
            if not buf:
                return
            payload = "".join(buf)
            payload_bytes = self._buffer_bytes.get(session_id, len(payload.encode("utf-8")))
            path = self._current_path(session_id, additional_bytes=payload_bytes)
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                with path.open("a", encoding="utf-8") as f:
                    f.write(payload)
                    f.flush()
                    try:
                        os.fsync(f.fileno())
                    except OSError:  # pragma: no cover — fsync may fail on some FS
                        pass
            except OSError as exc:  # pragma: no cover
                logger.warning("memory flush failed for %s: %s", session_id, exc)
                return
            self._buffers[session_id] = []
            self._buffer_bytes[session_id] = 0
            self._last_flush[session_id] = time.monotonic()


# ─── helpers ────────────────────────────────────────────────────────────


def _safe_session_segment(session_id: str) -> str:
    """Strip path-traversal characters from a session id."""
    safe = "".join(c for c in session_id if c.isalnum() or c in "-_:.T+Z")
    return safe or "unknown"


def _enforce_budget(recall: Recall, budget_tokens: int) -> tuple[Recall, bool]:
    """Drop tier3, then tier2 sections from the tail until under budget.

    Returns the (possibly trimmed) Recall plus a flag telling the caller
    whether anything was dropped.
    """
    used = recall.used_tokens or sum(
        s.tokens for s in (*recall.tier1, *recall.tier2, *recall.tier3)
    )
    if used <= budget_tokens:
        if used != recall.used_tokens:
            recall = Recall(
                tier1=recall.tier1,
                tier2=recall.tier2,
                tier3=recall.tier3,
                used_tokens=used,
                trace_id=recall.trace_id,
            )
        return recall, False

    tier3 = list(recall.tier3)
    tier2 = list(recall.tier2)
    tier1 = list(recall.tier1)
    while tier3 and used > budget_tokens:
        used -= tier3.pop().tokens
    while tier2 and used > budget_tokens:
        used -= tier2.pop().tokens
    # Tier 1 is sacred — never dropped. If we still overflow, just live
    # with it; recall_trace records dropped="over_budget" anyway.
    return (
        Recall(
            tier1=tier1,
            tier2=tier2,
            tier3=tier3,
            used_tokens=used,
            trace_id=recall.trace_id,
        ),
        True,
    )


# ─── Process-wide accessor ───────────────────────────────────────────────


_singleton_lock = threading.Lock()
_singleton: Optional[MemoryManager] = None


def get_memory() -> MemoryManager:
    """Return the process-wide MemoryManager."""
    global _singleton
    if _singleton is not None:
        return _singleton
    with _singleton_lock:
        if _singleton is None:
            _singleton = MemoryManager()
        return _singleton


def reset_for_tests(
    *,
    root: Optional[Path] = None,
    init_git: bool = False,
    rotation_bytes: int = _DEFAULT_ROTATION_BYTES,
) -> MemoryManager:
    """Replace the singleton with a fresh one (optionally rooted at a tmp dir).

    ``init_git=False`` is the default for tests so we don't shell out to
    git on every test.
    """
    global _singleton
    with _singleton_lock:
        _singleton = MemoryManager(
            root=root,
            init_git=init_git,
            rotation_bytes=rotation_bytes,
        )
    return _singleton


def recall_two_stage(
    query: str,
    *,
    source: str = "transcripts",
    top_k: int = 5,
    filter: Optional[dict[str, Any]] = None,
    deadline_ms: int = 250,
) -> list[Any]:
    """Module-level re-export of ``backend.memory.retriever.recall_two_stage``.

    Lives here so RecallPolicies (which already import from manager)
    don't have to know about the retriever submodule. Implementation is
    in :mod:`backend.memory.retriever`.
    """
    from backend.memory.retriever import recall_two_stage as _impl  # noqa: WPS433

    return _impl(
        query,
        source=source,
        top_k=top_k,
        filter=filter,
        deadline_ms=deadline_ms,
    )
